package org.idnp.jetpackpagingsample

import android.content.ContentValues.TAG
import android.os.Build
import android.util.Log
import androidx.annotation.RequiresApi
import com.google.firebase.database.DataSnapshot
import com.google.firebase.database.DatabaseError
import com.google.firebase.database.DatabaseReference
import com.google.firebase.database.ValueEventListener
import com.google.firebase.database.ktx.database
import com.google.firebase.database.ktx.getValue
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.ktx.Firebase
import org.json.JSONArray
import org.json.JSONObject

class ExampleBackendService {
    val movies = arrayListOf<Movie>()

    @RequiresApi(Build.VERSION_CODES.O)
    fun searchMovies(nextPageNumber: Int): List<Movie> {
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Crime|Drama|Romance|Thriller",name="Air I Breathe, The",qualification=8,releaseDay=11,releaseMonth=10,releaseYear=1945))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Horror|Sci-Fi|Thriller",name="Tentacles (Tentacoli)",qualification=3,releaseDay=22,releaseMonth=5,releaseYear=1947))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="The Private Life of Deer",qualification=3,releaseDay=21,releaseMonth=8,releaseYear=1944))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Policeman (Ha-shoter)",qualification=1,releaseDay=29,releaseMonth=3,releaseYear=1961))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="M for Mother (Mim mesle madar)",qualification=9,releaseDay=9,releaseMonth=2,releaseYear=1929))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Ladybird Ladybird",qualification=7,releaseDay=11,releaseMonth=7,releaseYear=1951))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|War",name="Beneath Hill 60",qualification=10,releaseDay=30,releaseMonth=5,releaseYear=1971))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Angel at My Table, An",qualification=3,releaseDay=20,releaseMonth=6,releaseYear=1939))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Horror|Sci-Fi",name="Swarm, The",qualification=7,releaseDay=22,releaseMonth=11,releaseYear=1997))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Animation|Children|Comedy",name="Hoodwinked!",qualification=5,releaseDay=24,releaseMonth=8,releaseYear=1940))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="8 (8, the Play)",qualification=8,releaseDay=12,releaseMonth=1,releaseYear=1948))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Crime|Drama|Horror|Thriller",name="Hangover Square",qualification=3,releaseDay=30,releaseMonth=10,releaseYear=1962))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Horror",name="Wishing Stairs (Yeogo goedam 3: Yeowoo gyedan)",qualification=4,releaseDay=30,releaseMonth=9,releaseYear=1904))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="Beyond the Lights",qualification=10,releaseDay=21,releaseMonth=8,releaseYear=1975))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="Spinning Plates",qualification=10,releaseDay=17,releaseMonth=11,releaseYear=2009))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Adventure|Western",name="Wild Bunch, The",qualification=8,releaseDay=19,releaseMonth=10,releaseYear=1994))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Documentary",name="Seven Up!",qualification=5,releaseDay=30,releaseMonth=11,releaseYear=1930))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="3rd World Hero (Bayaning Third World)",qualification=4,releaseDay=11,releaseMonth=7,releaseYear=1918))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Documentary",name="Balseros (Cuban Rafters)",qualification=1,releaseDay=23,releaseMonth=2,releaseYear=1974))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Horror",name="Raw Meat (Death Line)",qualification=10,releaseDay=5,releaseMonth=3,releaseYear=2000))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy",name="Dorm Daze (National Lampoon Presents Dorm Daze)",qualification=9,releaseDay=19,releaseMonth=12,releaseYear=1991))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="When You Comin' Back, Red Ryder?",qualification=8,releaseDay=11,releaseMonth=5,releaseYear=1905))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Drama",name="Wassup Rockers",qualification=2,releaseDay=26,releaseMonth=12,releaseYear=2009))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama|Romance",name="Lonesome Jim",qualification=1,releaseDay=14,releaseMonth=1,releaseYear=1948))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy",name="Leave It to Beaver",qualification=10,releaseDay=14,releaseMonth=9,releaseYear=1984))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Documentary",name="Glorious Technicolor",qualification=10,releaseDay=1,releaseMonth=7,releaseYear=1950))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Apnea (Apnoia)",qualification=10,releaseDay=10,releaseMonth=11,releaseYear=2014))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Action|Adventure|Fantasy|Sci-Fi",name="Wolverine, The",qualification=1,releaseDay=16,releaseMonth=1,releaseYear=1980))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Hail Mary ('Je vous salue, Marie')",qualification=3,releaseDay=20,releaseMonth=12,releaseYear=1960))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Crime|Drama",name="Bodyguard, The (Karate Kiba)",qualification=10,releaseDay=23,releaseMonth=6,releaseYear=1904))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Documentary",name="Venus Boyz",qualification=9,releaseDay=14,releaseMonth=5,releaseYear=2004))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Documentary|Musical",name="Etoiles: Dancers of the Paris Opera Ballet (Tout Près des étoiles)",qualification=6,releaseDay=19,releaseMonth=9,releaseYear=1982))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Crime|Film-Noir|Mystery|Romance",name="Fallen Angel",qualification=3,releaseDay=23,releaseMonth=9,releaseYear=1943))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|War",name="Misérables, Les",qualification=7,releaseDay=21,releaseMonth=8,releaseYear=1980))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Driving Miss Daisy",qualification=2,releaseDay=17,releaseMonth=8,releaseYear=1952))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy",name="Orgazmo",qualification=2,releaseDay=7,releaseMonth=7,releaseYear=1995))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="Gambler, The (Játékos, A)",qualification=5,releaseDay=11,releaseMonth=9,releaseYear=1979))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy",name="Bank Dick, The",qualification=1,releaseDay=1,releaseMonth=4,releaseYear=1978))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Children|Drama|Fantasy",name="Christmas Story (Joulutarina)",qualification=1,releaseDay=1,releaseMonth=2,releaseYear=1919))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Crime|Drama|Thriller",name="Taxi Driver",qualification=4,releaseDay=14,releaseMonth=1,releaseYear=1981))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Very Natural Thing, A",qualification=4,releaseDay=26,releaseMonth=12,releaseYear=1916))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Thriller",name="Assault, The (L'assaut)",qualification=9,releaseDay=24,releaseMonth=10,releaseYear=1909))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Drama|Romance",name="Seeking a Friend for the End of the World",qualification=6,releaseDay=30,releaseMonth=12,releaseYear=1908))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Thriller",name="American Roulette",qualification=5,releaseDay=15,releaseMonth=7,releaseYear=1915))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Documentary",name="War Room, The",qualification=1,releaseDay=21,releaseMonth=1,releaseYear=1945))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="After Death (Posle smerti)",qualification=10,releaseDay=16,releaseMonth=2,releaseYear=2006))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama",name="Village Barbershop, The",qualification=7,releaseDay=17,releaseMonth=8,releaseYear=2019))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Romance",name="Paris, I Love You (Paris, je t'aime)",qualification=7,releaseDay=9,releaseMonth=2,releaseYear=1973))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="Horror Business",qualification=9,releaseDay=28,releaseMonth=10,releaseYear=2017))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Crime|Documentary",name="American Drug War: The Last White Hope",qualification=10,releaseDay=2,releaseMonth=6,releaseYear=2015))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="Poor Boy's Game",qualification=1,releaseDay=30,releaseMonth=5,releaseYear=1990))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy",name="Welcome to the Sticks (Bienvenue chez les Ch'tis)",qualification=10,releaseDay=23,releaseMonth=8,releaseYear=1950))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Horror|Thriller",name="Housebound",qualification=10,releaseDay=2,releaseMonth=11,releaseYear=1964))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Animation|Children|Comedy",name="Tortoise and the Hare, The",qualification=7,releaseDay=2,releaseMonth=8,releaseYear=1949))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Crime|Drama|Romance|Thriller",name="Dead Man Down",qualification=5,releaseDay=19,releaseMonth=11,releaseYear=1949))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama|Thriller",name="Brimstone and Treacle",qualification=5,releaseDay=30,releaseMonth=2,releaseYear=1998))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Crime|Drama|Mystery|Thriller",name="Dark Alibi",qualification=1,releaseDay=12,releaseMonth=10,releaseYear=2000))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Edvard Munch",qualification=7,releaseDay=5,releaseMonth=4,releaseYear=1928))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Beau Pere (a.k.a. Stepfather) (Beau-père)",qualification=5,releaseDay=13,releaseMonth=9,releaseYear=1920))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Drama",name="Bonjour Monsieur Shlomi (Ha-Kochavim Shel Shlomi)",qualification=3,releaseDay=14,releaseMonth=12,releaseYear=1998))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Romance",name="Princess Diaries 2: Royal Engagement, The",qualification=10,releaseDay=1,releaseMonth=11,releaseYear=1973))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="Digging for Fire",qualification=3,releaseDay=10,releaseMonth=4,releaseYear=1954))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Romance",name="They Came Together",qualification=4,releaseDay=12,releaseMonth=8,releaseYear=2011))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Fantasy|Sci-Fi",name="The Invisible Boy",qualification=6,releaseDay=12,releaseMonth=7,releaseYear=1989))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama|Film-Noir",name="Moontide",qualification=4,releaseDay=28,releaseMonth=7,releaseYear=1917))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Western",name="Buchanan Rides Alone",qualification=5,releaseDay=5,releaseMonth=10,releaseYear=1970))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Kukuli",qualification=3,releaseDay=26,releaseMonth=1,releaseYear=1909))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Comedy|Crime",name="Silver Streak",qualification=4,releaseDay=21,releaseMonth=2,releaseYear=1947))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy",name="Hot to Trot",qualification=7,releaseDay=15,releaseMonth=9,releaseYear=1964))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Adventure|Drama",name="Norte, El",qualification=10,releaseDay=20,releaseMonth=12,releaseYear=2018))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Desert Bloom",qualification=2,releaseDay=3,releaseMonth=12,releaseYear=2011))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Adventure|Comedy|Sci-Fi",name="Paul",qualification=4,releaseDay=18,releaseMonth=7,releaseYear=2019))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Adventure|Children",name="The Search for Santa Paws",qualification=7,releaseDay=12,releaseMonth=5,releaseYear=2014))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Adventure|Children|Comedy|Mystery",name="Scooby-Doo 2: Monsters Unleashed",qualification=7,releaseDay=15,releaseMonth=12,releaseYear=1923))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama|Romance",name="Amira & Sam",qualification=3,releaseDay=5,releaseMonth=2,releaseYear=1985))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Horror|Thriller",name="Seance (Kôrei)",qualification=1,releaseDay=3,releaseMonth=8,releaseYear=1983))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Adventure|Western",name="Face to Face (Faccia a faccia)",qualification=3,releaseDay=2,releaseMonth=3,releaseYear=1977))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Oleanna",qualification=4,releaseDay=22,releaseMonth=4,releaseYear=1951))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama|Romance|Thriller",name="Montana Sky",qualification=10,releaseDay=24,releaseMonth=4,releaseYear=1901))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Children|Fantasy",name="Fairly Odd movies.add(Movie: Grow Up, Timmy Turner!, A",qualification=3,releaseDay=13,releaseMonth=4,releaseYear=1974))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Drama",name="Métisse (Café au Lait)",qualification=3,releaseDay=2,releaseMonth=12,releaseYear=1954))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="The Princess of Egypt",qualification=1,releaseDay=16,releaseMonth=1,releaseYear=1930))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Horror",name="Dunwich Horror, The",qualification=6,releaseDay=7,releaseMonth=7,releaseYear=1965))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Crime|Sci-Fi",name="World on a Wire (Welt am Draht)",qualification=5,releaseDay=26,releaseMonth=12,releaseYear=1964))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy",name="Game Plan, The",qualification=2,releaseDay=7,releaseMonth=1,releaseYear=2007))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama|Romance",name="Good Dick",qualification=7,releaseDay=19,releaseMonth=1,releaseYear=2007))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Horror|Sci-Fi",name="Watchers",qualification=9,releaseDay=6,releaseMonth=7,releaseYear=1954))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Romance|War",name="Toward the Unknown",qualification=4,releaseDay=11,releaseMonth=8,releaseYear=1976))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Crime|Drama",name="Cyclo (Xich lo)",qualification=8,releaseDay=9,releaseMonth=8,releaseYear=1979))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="Lost, Lost, Lost ",qualification=4,releaseDay=4,releaseMonth=3,releaseYear=1976))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Crime|Drama|Thriller",name="Lookout, The",qualification=8,releaseDay=7,releaseMonth=11,releaseYear=2000))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Lebanon, Pa.",qualification=4,releaseDay=28,releaseMonth=3,releaseYear=1953))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Film-Noir|Mystery",name="Fingers at the Window",qualification=9,releaseDay=15,releaseMonth=3,releaseYear=1947))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Crime|Thriller",name="Headhunters (Hodejegerne)",qualification=4,releaseDay=7,releaseMonth=3,releaseYear=2009))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Western",name="The Vanishing American",qualification=10,releaseDay=16,releaseMonth=10,releaseYear=1920))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Crime|Drama|Film-Noir|Mystery",name="Kansas City Confidential",qualification=10,releaseDay=8,releaseMonth=2,releaseYear=1933))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Romance",name="God is Great, I'm Not (Dieu est grand, je suis toute petite)",qualification=5,releaseDay=3,releaseMonth=3,releaseYear=1909))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Mystery|Thriller",name="Talented Mr. Ripley, The",qualification=2,releaseDay=10,releaseMonth=7,releaseYear=1919))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Fantasy|Horror|Thriller",name="Evil Dead, The",qualification=6,releaseDay=6,releaseMonth=8,releaseYear=1941))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="Hiroshima ",qualification=1,releaseDay=19,releaseMonth=12,releaseYear=1989))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Adventure|Drama|Romance|War",name="El Cid",qualification=9,releaseDay=1,releaseMonth=1,releaseYear=1972))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Romance",name="Prince & Me II: The Royal Wedding, The",qualification=4,releaseDay=3,releaseMonth=12,releaseYear=1953))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama|Romance",name="About Last Night...",qualification=7,releaseDay=29,releaseMonth=7,releaseYear=1926))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Action|Sci-Fi|Thriller",name="Blade Runner",qualification=8,releaseDay=19,releaseMonth=10,releaseYear=1944))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Horror|Thriller",name="The Invitation",qualification=3,releaseDay=1,releaseMonth=11,releaseYear=1904))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Adventure|Drama",name="Wyatt Earp's Revenge",qualification=4,releaseDay=1,releaseMonth=7,releaseYear=1935))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Horror|Romance|Thriller",name="A Girl Walks Home Alone at Night",qualification=7,releaseDay=23,releaseMonth=8,releaseYear=1901))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Queen to Play (Joueuse)",qualification=3,releaseDay=24,releaseMonth=12,releaseYear=2014))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Romance",name="Conquest",qualification=6,releaseDay=16,releaseMonth=2,releaseYear=1965))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="I'll Cry Tomorrow",qualification=8,releaseDay=22,releaseMonth=9,releaseYear=1904))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Comedy",name="They Call Him Bulldozer (Lo chiamavano Bulldozer)",qualification=8,releaseDay=25,releaseMonth=8,releaseYear=1978))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy",name="To Rome with Love",qualification=7,releaseDay=2,releaseMonth=12,releaseYear=1990))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Romance",name="Matchmaker, The",qualification=5,releaseDay=10,releaseMonth=6,releaseYear=1963))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Crime|Documentary",name="Serial Killer Culture",qualification=2,releaseDay=12,releaseMonth=7,releaseYear=2006))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Documentary",name="Spend It All",qualification=5,releaseDay=26,releaseMonth=2,releaseYear=1906))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Animation|Film-Noir|Sci-Fi|Thriller",name="Renaissance",qualification=9,releaseDay=15,releaseMonth=9,releaseYear=1936))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="Hollywood and The Pentagon: A Dangerous Liaison",qualification=10,releaseDay=6,releaseMonth=5,releaseYear=1916))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama|Horror|Romance",name="I Will Follow You Into the Dark",qualification=2,releaseDay=29,releaseMonth=5,releaseYear=2016))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Mystery|Thriller",name="Come Sweet Death (Komm, süsser Tod)",qualification=1,releaseDay=18,releaseMonth=3,releaseYear=1996))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Documentary",name="Prodigal Sons",qualification=3,releaseDay=23,releaseMonth=8,releaseYear=2016))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama|War",name="Cross of Lorraine, The",qualification=8,releaseDay=25,releaseMonth=9,releaseYear=1972))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Adventure|Animation|Children|Comedy|Crime|Fantasy|Mystery",name="Who Framed Roger Rabbit?",qualification=3,releaseDay=15,releaseMonth=8,releaseYear=1938))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Romance",name="27 Dresses",qualification=8,releaseDay=9,releaseMonth=7,releaseYear=1951))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Documentary|IMAX",name="Titanica",qualification=7,releaseDay=13,releaseMonth=9,releaseYear=1978))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Romance",name="Misadventures of Margaret, The",qualification=8,releaseDay=19,releaseMonth=4,releaseYear=1913))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Mystery|Thriller",name="Uncovered",qualification=4,releaseDay=29,releaseMonth=1,releaseYear=2017))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Sling Blade",qualification=2,releaseDay=5,releaseMonth=11,releaseYear=2014))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Drama",name="Diary of a Mad Housewife",qualification=4,releaseDay=26,releaseMonth=3,releaseYear=1931))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="Sergeant, The",qualification=3,releaseDay=17,releaseMonth=6,releaseYear=2008))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama",name="Firemen's Ball, The (Horí, má panenko)",qualification=1,releaseDay=25,releaseMonth=3,releaseYear=1922))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Western",name="Man Called Gannon, A",qualification=1,releaseDay=16,releaseMonth=1,releaseYear=1959))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama|Romance",name="Night Catches Us",qualification=6,releaseDay=9,releaseMonth=2,releaseYear=1928))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Comedy|Romance",name="Stars and Bars",qualification=1,releaseDay=8,releaseMonth=9,releaseYear=1940))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Romance",name="Romantics Anonymous (Les émotifs anonymes)",qualification=10,releaseDay=6,releaseMonth=10,releaseYear=1902))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="Rollover",qualification=2,releaseDay=26,releaseMonth=2,releaseYear=1972))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy",name="Married to the Mob",qualification=9,releaseDay=22,releaseMonth=11,releaseYear=1985))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Importance of Tying Your Own Shoes, The (Hur många lingon finns det i världen?)",qualification=5,releaseDay=19,releaseMonth=5,releaseYear=1909))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Drama",name="Grandpa for Christmas, A (Bert & Becca)",qualification=1,releaseDay=3,releaseMonth=11,releaseYear=1985))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Action|Drama|War",name="Fallen, The",qualification=5,releaseDay=11,releaseMonth=7,releaseYear=1939))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="(no genres listed)",name="The Hearts of Age",qualification=9,releaseDay=23,releaseMonth=7,releaseYear=1955))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Two Days, One Night (Deux jours, une nuit)",qualification=2,releaseDay=20,releaseMonth=11,releaseYear=1992))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Fantasy|Sci-Fi",name="Godzilla, Mothra, and King Ghidorah: Giant Monsters All-Out Attack (Gojira, Mosura, Kingu Gidorâ: Daikaijû sôkôgeki) (Godzilla, Mothra and King Ghidorah: Giant Monsters All-Out Attack)",qualification=5,releaseDay=25,releaseMonth=3,releaseYear=1978))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Blot, The",qualification=5,releaseDay=9,releaseMonth=8,releaseYear=1939))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama|Sci-Fi|IMAX",name="Transcendence",qualification=3,releaseDay=17,releaseMonth=1,releaseYear=1920))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Horror",name="Death Ship",qualification=6,releaseDay=19,releaseMonth=11,releaseYear=1961))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama",name="Jack",qualification=1,releaseDay=18,releaseMonth=2,releaseYear=1985))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama|Romance",name="Mélo",qualification=4,releaseDay=15,releaseMonth=1,releaseYear=1914))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Fantasy|Horror",name="Underworld",qualification=6,releaseDay=17,releaseMonth=2,releaseYear=1938))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Horror|Sci-Fi|Thriller",name="Mimic 2",qualification=3,releaseDay=13,releaseMonth=3,releaseYear=1939))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Molokai (Molokai: The Story of Father Damien)",qualification=10,releaseDay=2,releaseMonth=1,releaseYear=2014))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Animation|Drama|Fantasy|Mystery",name="Colourful (Karafuru)",qualification=4,releaseDay=21,releaseMonth=12,releaseYear=1978))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Documentary|Horror",name="Document of the Dead",qualification=7,releaseDay=28,releaseMonth=6,releaseYear=1970))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Romance|War",name="Big Parade, The",qualification=5,releaseDay=28,releaseMonth=2,releaseYear=2020))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|War",name="Island at War",qualification=3,releaseDay=25,releaseMonth=9,releaseYear=1973))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Thriller",name="Bandaged",qualification=8,releaseDay=19,releaseMonth=9,releaseYear=1976))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Western",name="Great Silence, The (Grande silenzio, Il)",qualification=5,releaseDay=7,releaseMonth=7,releaseYear=1985))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Adventure|Children",name="Gold Diggers: The Secret of Bear Mountain",qualification=2,releaseDay=1,releaseMonth=9,releaseYear=2018))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy",name="Animal House",qualification=7,releaseDay=6,releaseMonth=10,releaseYear=1966))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Scenes From a Marriage (Scener ur ett äktenskap)",qualification=1,releaseDay=22,releaseMonth=4,releaseYear=1973))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama|Romance",name="Lady is Willing, The",qualification=1,releaseDay=12,releaseMonth=3,releaseYear=1949))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Café de Flore",qualification=10,releaseDay=7,releaseMonth=8,releaseYear=1907))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Romance",name="White Massai, The (Weisse Massai, Die)",qualification=8,releaseDay=19,releaseMonth=9,releaseYear=1941))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Comedy|Romance|Thriller",name="So Close (Chik Yeung Tin Sai)",qualification=7,releaseDay=8,releaseMonth=2,releaseYear=1991))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="(no genres listed)",name="Onionhead",qualification=3,releaseDay=30,releaseMonth=9,releaseYear=1937))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy|Drama|Romance",name="Summer's Tale, A (Conte d'été)",qualification=2,releaseDay=14,releaseMonth=3,releaseYear=2018))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="All Fall Down",qualification=9,releaseDay=10,releaseMonth=3,releaseYear=2015))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy",name="Fat Kid Rules the World",qualification=9,releaseDay=14,releaseMonth=4,releaseYear=1901))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Crime",name="Triggermen",qualification=7,releaseDay=3,releaseMonth=2,releaseYear=1957))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Romance",name="Simply Irresistible",qualification=5,releaseDay=1,releaseMonth=7,releaseYear=1947))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Action|Adventure",name="Good Man in Africa, A",qualification=9,releaseDay=2,releaseMonth=2,releaseYear=1961))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="September",qualification=1,releaseDay=28,releaseMonth=8,releaseYear=1968))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama|Romance",name="Humoresque",qualification=10,releaseDay=19,releaseMonth=10,releaseYear=1980))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Documentary",name="Jonestown: The Life and Death of Peoples Temple",qualification=5,releaseDay=30,releaseMonth=8,releaseYear=1996))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="Shadow Boxers",qualification=8,releaseDay=23,releaseMonth=3,releaseYear=1921))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Comedy",name="Houseguest",qualification=4,releaseDay=16,releaseMonth=4,releaseYear=1934))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="(no genres listed)",name="Fist of Jesus",qualification=5,releaseDay=21,releaseMonth=2,releaseYear=1981))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama",name="Samson and Delilah",qualification=2,releaseDay=8,releaseMonth=10,releaseYear=2007))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Horror|Thriller",name="Quicksilver Highway",qualification=3,releaseDay=27,releaseMonth=1,releaseYear=1938))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Drama",name="Lost Embrace (Abrazo partido, El)",qualification=5,releaseDay=11,releaseMonth=9,releaseYear=1926))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Abraham's Valley (Vale Abraão)",qualification=7,releaseDay=24,releaseMonth=8,releaseYear=1922))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Romance",name="Cinderella Story, A",qualification=8,releaseDay=7,releaseMonth=2,releaseYear=1914))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Comedy|Crime|Thriller",name="Formula 51",qualification=3,releaseDay=19,releaseMonth=3,releaseYear=1945))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Animation|Comedy",name="Big Buck Bunny",qualification=10,releaseDay=8,releaseMonth=9,releaseYear=1940))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Romance|Western",name="Giant",qualification=10,releaseDay=2,releaseMonth=8,releaseYear=1980))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Children|Drama",name="The Jackie Robinson Story",qualification=1,releaseDay=28,releaseMonth=6,releaseYear=1940))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama",name="Vivre sa vie: Film en douze tableaux (My Life to Live)",qualification=4,releaseDay=22,releaseMonth=10,releaseYear=1987))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Horror|Thriller",name="Finders Keepers",qualification=4,releaseDay=12,releaseMonth=5,releaseYear=2006))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Documentary",name="Que Viva Mexico (¡Que Viva Mexico! - Da zdravstvuyet Meksika!)",qualification=7,releaseDay=16,releaseMonth=11,releaseYear=1967))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Musical",name="À nous la liberté (Freedom for Us)",qualification=5,releaseDay=25,releaseMonth=6,releaseYear=1973))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama",name="Invincible",qualification=1,releaseDay=15,releaseMonth=7,releaseYear=1934))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Comedy|Mystery|Thriller",name="Zero Effect",qualification=10,releaseDay=3,releaseMonth=5,releaseYear=1964))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Crime|Drama|Romance",name="Wonderful Crook, The (Pas si méchant que ça)",qualification=7,releaseDay=11,releaseMonth=8,releaseYear=2008))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Drama|Horror|Mystery|Thriller",name="House of 9",qualification=7,releaseDay=9,releaseMonth=6,releaseYear=1924))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Action|Drama|War",name="Seal Team Eight: Behind Enemy Lines",qualification=5,releaseDay=2,releaseMonth=9,releaseYear=1921))
        movies.add(Movie(description="Lo que sucede es que el personaje principal...",gender="Documentary",name="Punk Syndrome, The (Kovasikajuttu)",qualification=5,releaseDay=7,releaseMonth=1,releaseYear=2000))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Comedy|Drama|Mystery",name="Septien",qualification=9,releaseDay=14,releaseMonth=6,releaseYear=1977))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Crime|Drama",name="Killer: A Journal of Murder",qualification=2,releaseDay=7,releaseMonth=10,releaseYear=1932))
        movies.add(Movie(description="Alguna vez te preguntaste que pasa si....",gender="Drama|Romance",name="Roads to Koktebel (Koktebel)",qualification=10,releaseDay=25,releaseMonth=7,releaseYear=2015))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Action|Comedy|Crime|Romance|Thriller",name="The Squeeze",qualification=8,releaseDay=3,releaseMonth=8,releaseYear=1933))
        movies.add(Movie(description="Esta película tiene esta trama....",gender="Drama|War",name="55 Days at Peking",qualification=2,releaseDay=12,releaseMonth=8,releaseYear=1985))
        return movies
    }
}

data class ResponseUser(val movies: List<Movie>, val nextPageNumber: Int)